# Generated by Django 3.0.8 on 2020-07-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailactivation',
            name='activation_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
